# Generated by Django 5.0.2 on 2024-02-26 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=100)),
                ('material_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.material')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.process')),
            ],
        ),
        migrations.CreateModel(
            name='ProductProcess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.process')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Backend.product')),
            ],
        ),
    ]
