# Generated by Django 5.0.2 on 2024-02-27 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0003_material_processmaterial_productprocess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processmaterial',
            name='process',
        ),
        migrations.AddField(
            model_name='processmaterial',
            name='process_product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Backend.productprocess'),
        ),
    ]
