# Generated by Django 5.0.2 on 2024-03-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0004_remove_processmaterial_process_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
