# Generated by Django 5.0.2 on 2024-03-01 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Backend', '0005_alter_process_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='process',
            name='duration',
            field=models.IntegerField(default=0),
        ),
    ]
